from bs4 import BeautifulSoup
import requests
import wget
import os


def pdf_link_scraper(html):
    """this function scrapes CIA web-page with
    one-page summaries of the countries
    """
    links = {}

    with open(html) as html_file:
        soup = BeautifulSoup(html_file, "lxml")

    couyntry_data = soup.find_all("div", class_="country-name")

    for country in couyntry_data:
        links[country.text[1:-1]] = str(country)[38 : str(country).find("pdf") + 3]

    return links


def download_pdf(country, link):
    """this function takes list of links, generated by pdf_link_scraper()
    creates folder "pdf" and downloads one-page summaries for each country
    """

    link_to_pdf = (
        "https://www.cia.gov/library/publications/resources/the-world-factbook/" + link
    )

    if not os.path.exists("pdf"):
        os.mkdir("pdf")

    file_name = country + ".pdf"
    file_path = os.path.join("data", file_name)

    wget.download(link_to_pdf, file_path)


html = "cia.html"

links = pdf_link_scraper(html)

for country, link in links.items():
    download_pdf(country, link)
