from bs4 import BeautifulSoup
import requests
import wget
import os


def pdf_link_scraper():
    """this function scrapes CIA web-page with
    one-page summaries of the countries

    """
    links = {}
    cia_page = "https://www.cia.gov/library/publications/resources/the-world-factbook/docs/one_page_summaries.html"

    source = requests.get(cia_page).text
    soup = BeautifulSoup(source, "lxml")

    couyntry_data = soup.find_all("div", class_="country-name")

    for country in couyntry_data:
        link_for_country = (
            "https://www.cia.gov/library/publications/resources/the-world-factbook"
            + str(country.a["href"])[2:]
        )

        links[country.text[1:-1]] = link_for_country

    return links


def download_pdf(country, link):
    """this function takes list of links, generated by pdf_link_scraper()
    creates folder "pdf" and downloads one-page summaries for each country
    """

    if not os.path.exists("pdf"):
        os.mkdir("pdf")

    file_name = country + ".pdf"
    file_path = os.path.join("pdf", file_name)

    wget.download(link, file_path)


links = pdf_link_scraper()
# for key, value in links.items():
#     print(key, value)

for country, link in links.items():
    download_pdf(country, link)

print("Finished downloading all PDFs")
